### ISSUE TITLE
토큰과 이더 분배에 관해서

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/tokyo-bot#2]
토큰
- 락커
- EOA
- 멀티시그

이더
- EOA
- 멀티시그

**Comment by hersheythings** [comment]
n_account_type":"m개 중 n번째 계정의 종류는 무엇인가요?(락커, EOA)",

(락커,EOA) => (멀티시그, EOA)로 바뀌어야하지 않나요 ?

**Comment by ggs134** [comment]
네 바꿔야되요
