### ISSUE TITLE
amount bonus issue

### ISSUE THREAD

**Issue by hersheythings** [Onther-Tech/tokyo-bot#7]
순서도 질문 "5-3. k번째 보너스 구간의 보너스 수량을 내림차순으로 적어주세요" 질문에서는 일단 json 흐름대로 가긴 했는데, 투자액에 따른 i) 절대액을 보너스로 줄 수도 있고 ii) 상대적 퍼센트를 보너스로 줄 수도 있음. 이 둘은 질문으로 구분해줘야할 것 같음.

eg) 질문 ; **수량 보너스가 절대액인가요?** 
 - yes => i) k번째 보너스 구간의 보너스 **수량**을 내림차순으로 적어주세요
    
 - no => ii) k번째 보너스 구간의 보너스 **퍼센트**를 내림차순으로 적어주세요

**Comment by 4000D** [comment]
보너스는 상대적인 퍼센트만 가능합니다.
`coeff = 1000; base_rate = 100;`일 때
`time_bonus = 50; amount_bonus = 100;` 이면
`total_bonus = time_bonus + amount_bonus = 150;` 이고
`token_rate = base_rate * (coeff + total_bonus) / coeff = 100 * 1150 / 1000 = 115` 입니다

**Comment by ggs134** [comment]
절대액 보너스라고 해도, 기준가격 기준으로 역산해서 퍼센트 산출 가능하니 목적하는 결과에는 영향이 없을 것 같네요.
